stages:
  - Test

terraformv16:
  tags:
    - terraform
  stage: Test
  before_script:
    - echo "build terraform binary"
    - make fmt
    - go build
    - ls -lrt
  allow_failure: true
  script:
    - echo "Running tests on bigip version 16"
    - BIGIP_USER="$BIGIP_USERNAME_V16" BIGIP_PASSWORD="$BIGIP_PASSWORD_V16" BIGIP_HOST="$BIGIP_HOST_V16" TF_ACC=1 make testacc

terraformv15:
  tags:
    - terraform
  stage: Test
  before_script:  
    - echo "Running tests on bigip version 15"
    - ls -lrt
  allow_failure: true
  script:
    - BIGIP_USER="$BIGIP_USERNAME_V15" BIGIP_PASSWORD="$BIGIP_PASSWORD_V15" BIGIP_HOST="$BIGIP_HOST_V15" TF_ACC=1 make testacc

terraformv14:
  tags:
    - terraform
  stage: Test
  before_script:
    - echo "Running tests on bigip version 14"
    - ls -lrt
  script:  
    - BIGIP_USER="$BIGIP_USERNAME_V14" BIGIP_PASSWORD="$BIGIP_PASSWORD_V14" BIGIP_HOST="$BIGIP_HOST_V14" TF_ACC=1 make testacc
  

